# Generated by Django 2.2.1 on 2019-06-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V0toV17', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbs',
            name='v_grade',
            field=models.IntegerField(default=0),
        ),
    ]
