# Generated by Django 2.2.1 on 2019-06-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('V0toV17', '0002_climbs_v_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climbs',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='climbs',
            old_name='user_id',
            new_name='user',
        ),
    ]
