# Generated by Django 2.2.1 on 2019-06-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('V0toV17', '0003_auto_20190604_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbs',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='V0toV17.Session'),
        ),
    ]
