# Generated by Django 2.2.1 on 2019-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V0toV17', '0004_auto_20190604_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TechniquesManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UsersManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='techniques',
            unique_together={('technique_id', 'technique')},
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('first_name', 'last_name', 'dob')},
        ),
    ]
