# Generated by Django 2.2.1 on 2019-06-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('V0toV17', '0005_auto_20190610_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbs',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V0toV17.Session'),
        ),
    ]
